### PR TITLE
Styleguide and Screenshots, Change user name in data

### PR DESCRIPTION
**Pull request by scottvincent**
- ~~Removed the `<p>` tags from the data~~
- Changed the user name to match the photo
- tab v spaces in the `courses.json`
- Add `styleguide.md` and screenshots

[sc-184]
[sc-232]
[sc-228]
[sc-224]

### CODE REVIEW

**Comment by SezarGantousOSG** [comment]
I believe having an HTML tag in the data is part of the test to see how they handle parsing, is that correct @aubeOSG ?

**Comment by scottvincent** [comment]
@SezarGantousOSG Yeah fair enough, reverted

**Review by aubeOSG — CHANGES_REQUESTED** [review]
@scottvincent is the content a 1280 grid system like [adobe spectrum](https://spectrum.adobe.com/page/responsive-grid/)? Could you add a link to the grid system you used in the style guide?

This looks great by the way!

**Comment by scottvincent** [comment]
@aubeOSG Added a line about the max width being 1120. There isn't necessarily anything that needs a grid in here, and might leave it open to interpretation. 

To see how they handle smaller screens: 
1. they have min widths, flow to new row and expand to fill the space. 
2. they're fixed width cards and break to new row.
3. they're just set at 33% and they squash.
4. they ignore responsiveness and it breaks outside the page.

**Review by aubeOSG — APPROVED** [review]

**Pull request merged**
